### ISSUE TITLE
berkflow not suitable with chef-dk >= 0.11

### ISSUE THREAD

**Issue by scopenco** [reset/berkflow#15]
Hello,

berkflow 0.8.0 not suitable with chef-dk 0.11 and upper.

chef-dk installed
```
# rpm -q chefdk
chefdk-0.11.0-1.el6.x86_64
```

installing berkflow
```
[root@mwa-prundeck ~]# chef gem install berkflow -v 0.8.0
Fetching: wasabi-1.0.0.gem (100%)
Successfully installed wasabi-1.0.0
Fetching: nori-1.1.5.gem (100%)
Successfully installed nori-1.1.5
Fetching: httpi-0.9.7.gem (100%)
Successfully installed httpi-0.9.7
Fetching: akami-1.3.1.gem (100%)
Successfully installed akami-1.3.1
Fetching: savon-0.9.5.gem (100%)
Successfully installed savon-0.9.5
Fetching: rubyntlm-0.1.1.gem (100%)
Successfully installed rubyntlm-0.1.1
Fetching: logging-1.8.2.gem (100%)
Successfully installed logging-1.8.2
Fetching: gssapi-1.0.3.gem (100%)
Successfully installed gssapi-1.0.3
Fetching: winrm-1.1.3.gem (100%)
Successfully installed winrm-1.1.3
Fetching: ridley-connectors-2.4.0.gem (100%)
Successfully installed ridley-connectors-2.4.0
Fetching: octokit-3.8.0.gem (100%)
Successfully installed octokit-3.8.0
Fetching: solve-1.2.1.gem (100%)
Successfully installed solve-1.2.1
Fetching: berkshelf-4.0.1.gem (100%)
Successfully installed berkshelf-4.0.1
Fetching: berkflow-0.8.0.gem (100%)
Successfully installed berkflow-0.8.0
14 gems installed
```

running blo
```
# chef exec blo
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate berkshelf-4.2.1, because addressable-2.4.0 conflicts with addressable (~> 2.3.4) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1408:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:196:in `rescue in try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:193:in `try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/ascopenco/.chefdk/gem/ruby/2.1.0/gems/berkflow-0.8.0/lib/berkflow.rb:5:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ascopenco/.chefdk/gem/ruby/2.1.0/gems/berkflow-0.8.0/lib/berkflow/cli.rb:1:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ascopenco/.chefdk/gem/ruby/2.1.0/gems/berkflow-0.8.0/bin/blo:3:in `<top (required)>'
	from /home/ascopenco/.chefdk/gem/ruby/2.1.0/bin/blo:22:in `load'
	from /home/ascopenco/.chefdk/gem/ruby/2.1.0/bin/blo:22:in `<main>'
```

**Comment by JackChance** [comment]
I haven't seen this issue with chefdk 0.12.0, chefdk 0.13.21 or chefdk 0.15.16 and berkflow 0.8.0. Have you run 
`chef gem cleanup`
 to ensure that out of date gems aren't being referenced first in dependency chain, locking out more recent gems that are required? You can also try manually removing adressable 2.3.4 with 
`chef gem uninstall addressable -v 2.3.4` 
and see if that clears up your problem.
